#!/bin/bash

# Install Nginx
apt-get update
apt-get install nginx -y

# Open the default Nginx configuration file
nano /etc/nginx/sites-available/default

# Add location block for root URL
echo "location / {
    return 200 'Hello World!';
}" >> /etc/nginx/sites-available/default

# Restart Nginx
/etc/init.d/nginx restart
