#!/bin/bash

# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Set nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Create index.html containing "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html
